# Generated by Django 4.2.6 on 2024-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HasilKirim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("waktu_awal", models.TimeField()),
                ("waktu_akhir", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "History Hasil Kirim",
                "db_table": 'mytask"."hasil_kirim',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LogMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Log Aktifitas Menu",
                "db_table": 'mytask"."log_menu',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuProduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Menu Produk",
                "db_table": 'mytask"."menu_produk',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produk_id", models.CharField(max_length=64, unique=True)),
                ("nama", models.CharField(max_length=128)),
                ("norma_waktu", models.IntegerField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Produk",
                "db_table": 'mytask"."produk',
                "managed": True,
            },
        ),
    ]
