# Generated by Django 4.2.6 on 2024-11-30 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mytask", "0001_initial"),
        ("uman", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuproduk",
            name="menu",
            field=models.ManyToManyField(to="uman.menu"),
        ),
        migrations.AddField(
            model_name="menuproduk",
            name="produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mytask.produk"
            ),
        ),
        migrations.AddField(
            model_name="logmenu",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uman.menu",
            ),
        ),
        migrations.AddField(
            model_name="hasilkirim",
            name="produk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="mytask.produk"
            ),
        ),
        migrations.AddField(
            model_name="hasilkirim",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
