# Generated by Django 4.2.6 on 2025-05-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabKota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alt_nama', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kabkota',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alt_nama', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('kabkota', models.ForeignKey(db_column='kabkota_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.kabkota')),
            ],
            options={
                'db_table': 'kecamatan',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alt_nama', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('kecamatan', models.ForeignKey(db_column='kecamatan_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.kecamatan')),
            ],
            options={
                'db_table': 'kelurahan',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('alt_nama', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provinsi',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'vitamin',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.CharField(blank=True, max_length=250, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('hp_informasi', models.CharField(blank=True, max_length=20, null=True)),
                ('gps_koordinat', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('kepala_puskesmas', models.CharField(blank=True, max_length=100, null=True)),
                ('kelurahan', models.ForeignKey(db_column='kelurahan_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.kelurahan')),
            ],
            options={
                'db_table': 'puskesmas',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='kabkota',
            name='provinsi',
            field=models.ForeignKey(db_column='provinsi_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.provinsi'),
        ),
    ]
