# Generated by Django 4.2.6 on 2025-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelurahan',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
