# Generated by Django 4.2.6 on 2025-06-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0002_alter_kelurahan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=150, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'satuan',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.CharField(blank=True, max_length=250, null=True)),
                ('jenjang', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA')], max_length=10)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('kelurahan', models.ForeignKey(db_column='kelurahan_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.kelurahan')),
                ('puskesmas', models.ForeignKey(db_column='puskesmas_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.puskesmas')),
            ],
            options={
                'db_table': 'sekolah',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
