# Generated by Django 4.2.6 on 2025-06-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0003_satuan_sekolah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stokobat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_terima', models.DateTimeField(blank=True, null=True)),
                ('terima', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('puskesmas', models.ForeignKey(db_column='puskesmas_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.puskesmas')),
                ('satuan', models.ForeignKey(db_column='satuan_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.satuan')),
                ('vitamin', models.ForeignKey(db_column='vitamin_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.vitamin')),
            ],
            options={
                'db_table': 'stok_obat',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distribusisiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=10, null=True)),
                ('nama_siswa', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('tgl_terima', models.DateTimeField(blank=True, null=True)),
                ('kelas', models.CharField(blank=True, max_length=10, null=True)),
                ('sekolah', models.ForeignKey(db_column='sekolah_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.sekolah')),
                ('vitamin', models.ForeignKey(db_column='vitamin_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.vitamin')),
            ],
            options={
                'db_table': 'distribusi_siswa',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distribusiobat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_kirim', models.DateTimeField(blank=True, null=True)),
                ('tgl_terima', models.DateTimeField(blank=True, null=True)),
                ('jumlah_terima', models.IntegerField(blank=True, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('puskesmas', models.ForeignKey(db_column='puskesmas_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.puskesmas')),
                ('sekolah', models.ForeignKey(db_column='sekolah_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.sekolah')),
                ('stokobat', models.ForeignKey(db_column='stokobat_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.stokobat')),
            ],
            options={
                'db_table': 'distribusi_obat',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
