# Generated by Django 4.2.6 on 2025-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0004_stokobat_distribusisiswa_distribusiobat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokobat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stokobat',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stokobat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stokobat',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
