# Generated by Django 4.2.6 on 2025-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0005_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puskesmas',
            name='kode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='kode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
