# Generated by Django 4.2.6 on 2025-07-15 14:08

from django.db import migrations, models
import modules.vitamin.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0006_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puskesmas',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puskesmas',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=modules.vitamin.models.custom_file_nama_gambar),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=modules.vitamin.models.custom_file_nama_gambar_sekolah),
        ),
    ]
