# Generated by Django 4.2.6 on 2025-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0007_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='gps_koordinat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
