# Generated by Django 4.2.6 on 2025-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0008_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stokobat',
            name='satuan',
        ),
        migrations.RemoveField(
            model_name='stokobat',
            name='vitamin',
        ),
        migrations.CreateModel(
            name='MasterObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pabrik', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('kadaluarsa', models.DateTimeField(blank=True, null=True)),
                ('isi', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('batchnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('satuan', models.ForeignKey(db_column='satuan_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.satuan')),
                ('vitamin', models.ForeignKey(db_column='vitamin_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.vitamin')),
            ],
            options={
                'db_table': 'master_obat',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stokobat',
            name='masterobat',
            field=models.ForeignKey(db_column='masterobat_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='vitamin.masterobat'),
        ),
    ]
