# Generated by Django 4.2.6 on 2025-07-31 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0009_remove_stokobat_satuan_remove_stokobat_vitamin_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='puskesmas',
            name='is_terdaftar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='puskesmas',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/puskesmas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'JPG', 'JPEG', 'PNG', 'svg', 'SVG'])]),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sekolah/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'JPG', 'JPEG', 'PNG', 'svg', 'SVG'])]),
        ),
    ]
