# Generated by Django 4.2.6 on 2025-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0010_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribusiobat',
            name='tgl_kirim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribusiobat',
            name='tgl_terima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribusisiswa',
            name='tgl_terima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterobat',
            name='kadaluarsa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stokobat',
            name='tgl_terima',
            field=models.DateField(blank=True, null=True),
        ),
    ]
