# Generated by Django 4.2.6 on 2025-08-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0011_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=45)),
                ('tmp_lahir', models.CharField(blank=True, max_length=45)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa', to='vitamin.sekolah')),
            ],
            options={
                'db_table': 'siswa',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='distribusisiswa',
            name='siswa',
            field=models.ForeignKey(db_column='siswa_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.siswa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SiswaHB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('hb', models.DecimalField(decimal_places=1, max_digits=4)),
                ('keterangan', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekam_hb', to='vitamin.siswa')),
            ],
            options={
                'verbose_name': 'Rekam HB Siswa',
                'verbose_name_plural': 'Rekam HB Siswa',
                'db_table': 'siswa_hb',
                'indexes': [models.Index(fields=['siswa', 'tahun'], name='siswa_hb_siswa_i_0e0fb2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='siswa',
            index=models.Index(fields=['nis'], name='siswa_nis_ef017b_idx'),
        ),
        migrations.AddIndex(
            model_name='siswa',
            index=models.Index(fields=['sekolah'], name='siswa_sekolah_9c9c28_idx'),
        ),
    ]
