# Generated by Django 4.2.6 on 2025-08-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0012_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='distribusisiswa',
            name='distribusiobat',
            field=models.ForeignKey(db_column='distobat_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.distribusiobat'),
            preserve_default=False,
        )
    ]
