# Generated by Django 5.2.5 on 2025-10-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0013_alter_siswa_options_distribusiobat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='stokobat',
            name='masterobat',
            field=models.ForeignKey(db_column='masterobat_id', on_delete=django.db.models.deletion.CASCADE, to='vitamin.masterobat'),
        ),
    ]
