# Generated by Django 5.2.5 on 2025-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0014_distribusiobat_created_at_distribusiobat_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokobat',
            name='butir',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
