# Generated by Django 5.2.5 on 2025-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0016_populate_butir'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribusiobat',
            name='butir',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
