"""
Django settings for prototype project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gfal(vfmsc!_3nt5+p%&0huac3xeoi3wfjx*h)rvuc#^a-_88!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

WEB_MODE = os.getenv("WEB_MODE", "production").strip().lower()
if WEB_MODE not in {"production", "developer"}:
    WEB_MODE = "production"

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://modiva.nurulfikri.ac.id",
    "https://modiva.depoksehat.id"
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'modules.uman',  # User management
    'modules.core',
    'modules.mytask',
    #'modules.info',
    'widget_tweaks',
    'rest_framework',
    'django_filters',
    'django_htmx',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'django_select2',
    'defender', # Anti brute force login
    'auditlog',
    'wkhtmltopdf',
    'modules.vitamin',
    'modules.landingpage',
    'modules.peta',  # New Peta module
    'modules.vector',  # New Peta module
    'django.contrib.humanize',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'defender.middleware.FailedLoginMiddleware', #Middleware utk mencegah brute force login
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'modules.mytask.logging_access_middleware.MenuAccessLogsMiddleware',
    'auditlog.middleware.AuditlogMiddleware' ,
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(CORE_DIR, 'templates')
        ],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'modules.core.core_context_processor.UserDetails',
                #'modules.core.core_context_processor.BreadDict',
                #'modules.core.core_context_processor.Applications',
                'django.template.context_processors.media',  # MEDIA
            ],
           'loaders':[(
                'django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                    'django_components.template_loader.Loader',
                ]
           )],
            'builtins': [
                'django_components.templatetags.component_tags',
            ]

        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'db_modiva',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'root',
        'PASSWORD':'omset50juta',
        'HOST': 'localhost',
        'PORT': '3306',
    },

}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

#LANGUAGE_CODE = 'id-ID'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True
#USE_THOUSAND_SEPARATOR = True
#THOUSAND_SEPARATOR = '.'
LANGUAGE_CODE = 'id-ID'
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
#ROOT_URL = ''
ROOT_URL = ''
STATIC_URL = ROOT_URL + 'static/'
#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ADDITIONAL SETTING
# AUTH_USER_MODEL = 'uman.User'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / "components",
]
#STATIC_ROOT = BASE_DIR / 'static'



##########################################
# Additional setting put below
MEDIA_URL = ROOT_URL+'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
LOGIN_URL = ROOT_URL
HOSTNAME_FOR_TTE = 'http://localhost:8000'
WKHTMLTOPDF = '/usr/local/bin/wkhtmltopdf'

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_URL = '/login'

#Pengaturan terkait DRF
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser', 
        'rest_framework.renderers.JSONRenderer',
    ],
}

#Pengaturan terkait SSO 
SITE_ID = 1

#LOGIN_REDIRECT_URL = '/home/'
#LOGIN_REDIRECT_URL = '/' + ROOT_URL + 'home/'
LOGIN_REDIRECT_URL = '/' + ROOT_URL + 'sso_view'
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True


#Pengaturan SERVER EMAIL/SMTP
#EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
#EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
DEFAULT_FROM_EMAIL = 'system@dandes.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '172.17.0.1'
EMAIL_HOST_USER = 'system@dandes.com'
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 1025
EMAIL_USE_TLS = False

#Pengaturan Server Redis Message Broker
SIKD_REDIS_HOST=['127.0.0.1']
SIKD_REDIS_PASSWORD=''
SIKD_REDIS_PORT=6379
SIKD_REDIS_DB=1

#Pengaturan URL BASE dari beberapa serviec API yang diperlukan
API_BASE_URLS = {
  
}

# session expires in 3 hour
SESSION_COOKIE_AGE = 10800

DEFENDER_REDIS_URL = "redis://127.0.0.1:6379/1"
DEFENDER_BEHIND_REVERSE_PROXY=True
DEFENDER_LOGIN_FAILURE_LIMIT=5 
DEFENDER_LOCKOUT_TEMPLATE='includes/defender_lockout.html'

MYTASK_LOGGING_ENABLED=True
INCLUDE_EXAMPLES=True
if INCLUDE_EXAMPLES:
    INSTALLED_APPS += ['django_components','modules.examples']


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/general2.log', 
            },

    },
    'loggers': {
        #'django': {
        'modules.uman': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
       
    },
}
