# Generated by Django 4.2.6 on 2024-11-30 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="aplikasi"),
                ),
                (
                    "infografis",
                    models.ImageField(blank=True, null=True, upload_to="infografis"),
                ),
                (
                    "faw",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="faw"
                    ),
                ),
                ("urutan", models.IntegerField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="url"
                    ),
                ),
                ("as_modul", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Aplikasi",
            },
        ),
        migrations.CreateModel(
            name="GroupAplikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="name"),
                ),
                (
                    "abbr",
                    models.CharField(max_length=15, unique=True, verbose_name="abbr"),
                ),
                ("urutan", models.IntegerField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                (
                    "faw",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="faw"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Group Aplikasi",
            },
        ),
        migrations.CreateModel(
            name="Jabatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kd_jabatan", models.CharField(max_length=20, unique=True)),
                ("nm_jabatan", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Jabatan",
                "db_table": "uman_jabatan",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kd_unit", models.CharField(max_length=20, unique=True)),
                ("nm_unit", models.CharField(max_length=100, unique=True)),
                ("alamat", models.CharField(blank=True, max_length=200, null=True)),
                ("kota", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Unit",
                "db_table": "uman_unit",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_hp", models.CharField(blank=True, max_length=20, null=True)),
                ("no_wa", models.CharField(blank=True, max_length=20, null=True)),
                ("kdunit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "foto_profil",
                    models.ImageField(blank=True, upload_to="uman/foto_profil"),
                ),
                ("nip", models.CharField(blank=True, max_length=40, null=True)),
                ("nik", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "as_admin",
                    models.CharField(
                        blank=True,
                        choices=[("admin", "ADMIN"), ("operator", "OPERATOR")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Detail",
                "db_table": "uman_userdetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nip",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("nama", models.CharField(blank=True, max_length=100, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=20, null=True)),
                ("no_wa", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                (
                    "kd_jabatan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="uman.jabatan",
                    ),
                ),
                (
                    "kd_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="uman.unit",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pegawai",
                "db_table": "uman_pegawai",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="url"
                    ),
                ),
                ("urutan", models.IntegerField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
                ("faw", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("isembed", models.BooleanField(default=False)),
                (
                    "url_embed",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="url_embed"
                    ),
                ),
                ("as_beranda", models.BooleanField(default=False)),
                (
                    "aplikasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="uman.aplikasi"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_menu_set",
                        to="uman.menu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Menu",
            },
        ),
        migrations.CreateModel(
            name="GroupMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view",
                    models.CharField(
                        blank=True,
                        choices=[("admin", "ADMIN"), ("operator", "OPERATOR")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                ("menu", models.ManyToManyField(to="uman.menu")),
            ],
            options={
                "verbose_name_plural": "Group Menu",
                "db_table": "uman_groupmenu",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmbedMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secretkey",
                    models.CharField(max_length=255, verbose_name="secretkey"),
                ),
                (
                    "url_metabase",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL Metabase",
                    ),
                ),
                ("metabase_id", models.IntegerField(blank=True, null=True)),
                (
                    "param_tahun",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="uman.menu"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Embed Menu",
            },
        ),
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("namespace", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=64)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Konfigurasi Aplikasi",
                "managed": True,
                "unique_together": {("namespace", "key")},
            },
        ),
        migrations.AddField(
            model_name="aplikasi",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uman.groupaplikasi",
            ),
        ),
    ]
