# Generated by Django 5.2.5 on 2025-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmenu',
            name='can_view',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('operator puskesmas', 'OPERATOR PUSKESMAS'), ('operator sekolah', 'OPERATOR SEKOLAH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='as_admin',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('operator puskesmas', 'OPERATOR PUSKESMAS'), ('operator sekolah', 'OPERATOR SEKOLAH')], max_length=20, null=True),
        ),
    ]
